language: php

php:
  - 7.1
  - 7.2

services:
  - neo4j
  
sudo: false

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - travis_wait 30 vendor/bin/phpspec run

